index.js
lib/usbmux/transformer/usbmux-decoder.js
lib/usbmux/transformer/usbmux-encoder.js
lib/usbmux/usbmux.js
lib/util/transformer/length-based-splitter.js
lib/utilities.js
test/usbmux/usbmux-specs.js
test/utilities-specs.js

Add a little utility function, `getConnectedDevices`, to get just the connected udids without the client needing to know anything about dealing with the module (e.g., instantiating, finding the correct key for udid, etc.). This will allow us to replace https://github.com/appium/appium-xcuitest-driver/blob/master/lib/real-device-management.js#L6-L20 and get rid of the dependency on `idevice_id` in `appium-xcuitest-driver`.

Add getConnectedDevices utility function

---

index.js
lib/plist-service/index.js
lib/services.js
lib/ssl-helper.js
lib/utilities.js
test/utilities-specs.js

* Create a services object in order to avoid creating too many exports
* Create an utilities object to be consistent with the services object
* Create a ssl-helper since lockdown ssl and service ssl are shared
* Add ssl support for services which is mainly used in iOS 13

Refactor and add SSL enabled service support

---

lib/services.js

Shift from passing `socket` in as a named parameter, to passing an object that might have a `socket` property.
Also add another property for the `startWebInspectorService` function, to pass in the major OS version if we have it. This will allow us to use the function with sims (where we cannot get the OS version from this package).
As far as I can tell, in current usage the `socket` argument is not actually being used.

refactor: Pass opts to service creation functions

---

lib/util/transformer/length-based-splitter.js
lib/webinspector/index.js

When things like `source` for large webpage are called, it can overflow the maximum frame buffer.
This bumps it up to a still-reasonable value.
I will work on making this configurable to the end-user, but for now bigger will work.
Should fix https://github.com/appium/appium/issues/13229

fix: bump max frame size for web inspector service

---

lib/afc/index.js
lib/house-arrest/index.js
lib/notification-proxy/index.js
lib/plist-service/index.js
lib/simulatelocation/index.js
lib/syslog/index.js
lib/usbmux/index.js
lib/webinspector/index.js

The original problem has been uncovered by @KazuCocoa while checking https://github.com/appium/appium-xcuitest-driver/pull/1094
By calling socket.destroy we never send the FIN packet, so the server only closes connection after the timeout (30 seconds). See https://stackoverflow.com/questions/49268934/socket-in-close-wait-for-node-js-client for more details. In general, the `destroy` method of `net.Socket` is only recommended to be called in exceptional situations.

fix: prefer socket.end call to socket.destroy

---

lib/afc/index.js
lib/base-service.js
lib/house-arrest/index.js
lib/installation-proxy/index.js
lib/lockdown/index.js
lib/notification-proxy/index.js
lib/plist-service/index.js
lib/simulatelocation/index.js
lib/syslog/index.js
lib/usbmux/index.js
lib/webinspector/index.js

Recent changes have highlighted that there is a lot of shared code here. Get rid of that particular repetition.

refactor: move shared service code into base classes

---

lib/util/transformer/stream-logger.js
lib/webinspector/index.js

Add a logging transform, to get the bytes coming through. This could be used for any of the other processes, but right now is only needed for the Web Inspector.
Output mimics that of `iwdp` in verbose mode. Output for initial handshake within the `appium-xcuitest-driver`:
```
info RemoteDebugger Remote Debugger version 6.4.0
dbug RemoteDebugger useNewSafari --> false
dbug RemoteDebugger Checking which communication style to use (Safari on platform version '13.2')
dbug RemoteDebugger Platform version equal or higher than '12.2': true
WARN RemoteDebugger Setting communication protocol: using Target-based communication
dbug RemoteDebugger Sending connection key request
dbug RemoteDebugger Sending '_rpc_reportIdentifier:' message (id: 0)
dbug ios-device Sending message to Web Inspector:
dbug …
```

feat: fully log web inspector communication in verbose mode

---

lib/plist-service/transformer/plist-service-encoder.js
lib/services.js
lib/util/transformer/stream-logger.js
lib/utilities.js
lib/webinspector/index.js
lib/webinspector/transformer/webinspector-decoder.js
lib/webinspector/transformer/webinspector-socket.js
test/webinspector/webinspector-service-specs.js

On real devices larger blocks of data sent to the Web Inspector get stuck. Sending them in as chunks of data seems to fix the problem. The chunk size can be changed from 5000 bytes default, using the `socketChunkSize` option to the service (and service creator).
This also adds a `verboseHexDump` option in order to independently control the plain text logging of individual plists and the hex dump of all communication back and forth.

fix: send chunks of data to web inspector

---

lib/afc/index.js
lib/afc/protocol.js
lib/usbmux/index.js

While exploring the code, I did some cleanup. The only substantive change is moving from `_.noop()` (which is `undefined`) to `_.noop` (which is a null function) for the default callback on the `usbmux` and `afc` services.

refactor: clean up afc code

---

lib/afc/streams.js

Related to https://github.com/appium/appium/issues/13757#issuecomment-570640266
Internally these callbacks are not awaited, which means any errors there cause unhandled exceptions

fix: Change async callbacks to "classic" promise calls

---

lib/webinspector/index.js

Apparently webinspectord on iOS 10.x can't handle blank messages (sending such messages causes it to crash).
This PR prevents sending blank messages to webinspectord after every sent message.
Fixes https://github.com/appium/appium/issues/13825

fix: not sending blank messages to web inspector for iOS 10.x

---

lib/afc/index.js
lib/afc/streams.js
lib/afc/transformer/afcdecoder.js
lib/afc/transformer/afcencoder.js
lib/house-arrest/index.js
lib/notification-proxy/index.js
lib/plist-service/index.js
lib/plist-service/transformer/plist-service-decoder.js
lib/plist-service/transformer/plist-service-encoder.js
lib/services.js
lib/syslog/index.js
lib/syslog/transformer/syslog-decoder.js
lib/usbmux/index.js
lib/usbmux/transformer/usbmux-decoder.js
lib/usbmux/transformer/usbmux-encoder.js
lib/util/transformer/length-based-splitter.js
lib/util/transformer/stream-logger.js
lib/utilities.js
lib/webinspector/index.js
lib/webinspector/transformer/webinspector-decoder.js
lib/webinspector/transformer/webinspector-encoder.js
test/usbmux/usbmux-specs.js

This PR refactors two elements:
1. Moves `LengthBasedSplitter` to use options rather than a long list of parameters
1. Cleans up callbacks
1. Gets rid of most global eslint disabling, which can obscure bad patterns, and in most cases were unnecessary (e.g., callbacks not named `cb` or `callback` do not trigger the warning).
1. Gets rid of the connection callbacks, which were only used internally and just made the flow of information obscure. In all cases these could be handled by getting the socket and then doing whatever transformation was needed in the calling function.

refactor: clean up callbacks and long parameter constructor

---

lib/afc/index.js
lib/base-service.js
lib/house-arrest/index.js
lib/notification-proxy/index.js
lib/plist-service/index.js
lib/syslog/index.js
lib/usbmux/index.js
lib/utilities.js

Related to https://travis-ci.org/appium/appium-xcuitest-driver/jobs/646286301#L4794

fix: Fix possible unexpected EPIPE exceptions

---

lib/utilities.js

It looks Apple did change something recently in the lockdown protocol, so `TimeZoneOffsetFromUTC` does not return a [proper offset](https://discuss.appium.io/t/appium-1-17-getdevicetime-returns-strange-value/30162) anymore. I'll try to set the UTC offset based on the time zone name instead

feat: Add time zone name to the getDeviceTime result

---

lib/usbmux/index.js

On Windows, the equivalent of usbmuxd is the Apple Mobile Device Manager which runs on `127.0.0.1:27015`.
This PR modifies the `getDefaultSocket` routine to connect to `127.0.0.1:27015` when appium-ios-device (and hence, Appium) is running on WSL.
With this change, most of the appium-ios-device code runs correctly on WSL.

[feat] Connect to usbmuxd on 127.0.0.1:27015 when running on WSL1

---

lib/usbmux/index.js

Related to https://github.com/appium/appium-ios-device/pull/75
cc @qmfrederik

docs: Update the docstring of getDefaultSocket function

---

README.md
lib/utilities.js

No arg of `getValue` returns all of the available default values.
This data helps to get device info for debugging etc.

feat: extract get device values

---

lib/ssl-helper.js

iOS does not support TLS 1.0 anymore, and `secureProtocol` is Legacy mechanism to select the TLS protocol version to use, just use the default tls.DEFAULT_MIN_VERSION and tls.DEFAULT_MAX_VERSION

fix: SSL. Node.js v17 upgraded to OpenSSL 3.0, TLS 1.0 and 1.1 no longer working at the default security level of 1

---

README.md
index.js
lib/instrument/headers.js
lib/instrument/index.js
lib/instrument/transformer/dtx-encode.js
lib/services.js
lib/testmanagerd/index.js

testmanagerd  has almost same procedure with instruments with different channel or operation.
I'm still working on starting wda with appium-ios-device. due to #93 has not been updated for a long time.
Meanwhile, I found a bug that while using aux_buffer as input, `NSError` will always appear as no arguments are provided.
After some digging, I found the bug. The bug should be reproduced using following codes which are actually the initial parts of connecting testmanagerd: 
```nodejs
import { services } from 'appium-ios-device';
const { startInstrumentService } = services;
// Though using instruments server, this should work if messages are passed correctly
const x1 = await startInstrumentService(udid);
x1.registerUndefinedCallback((msg) => console.log('x1', msg));
const x1Daemon = await …
```

fix: the issue which auxBuffer cannot be correctly handled as parameter.

---

README.md
lib/base-service.js
lib/imagemounter/index.js
lib/imagemounter/utils/list_developer_image.js
lib/instrument/transformer/nskeyed.js
lib/services.js
lib/utilities.js
lib/xctest.js
test/imagemounter/list-developer-image-specs.js

This is for solving [#18450](https://github.com/appium/appium/issues/18450) which was caused by missing developer image on lower version of Xcode or other OS.
I add a new service and operates auto mount procedure while getting 'InvalidService' error on starting service.
Does it make sense if I move autoMountDeveloperImage to utilities and export as a function?

feat: Add ImageMounterService and auto fetch developer image if start service failed with 'InvalidService'

---

.github/workflows/publish.js.yml

The latest publishment failed as nodejs 18 compatibility issue
https://github.com/appium/appium-ios-device/actions/runs/7547941800/job/20548972866

chore: use latest lts for the publishment

---

lib/instrument/transformer/dtx-decode.js
lib/instrument/transformer/nskeyed.js

This does not fix the original issue (e.g. fixes DTX message parsing), but at least the node process itself does not die due to an unhandled exception.

fix: Avoid throwing of runtime exception if DTXMessage cannot be decoded

---

lib/xctest.js

This usage itself improves Appium's launching WDA method for ios 16 and lower since Appium uses `xcrun devicectl device process launch` for ios 17+. I have locally tested at least this didn't break anything.
(Inspired by https://github.com/danielpaulus/go-ios/pull/510)
https://github.com/appium/appium/issues/20270 for iOS 16 and lower should be improved. For iOS 17+, we need 3rd party such as go-ios. It looks like `xcrun devicectl device process launch` doesn't enable this.
Maybe... we also could add trobleshooting guid about:
```
3|appium bibit 3  | [IOSDeviceLog] Jun 24 10:04:11 iPhone-2 WebDriverAgentRunner-Runner(XCUIAutomation)[24467] <Error>: Failed to initialize for UI testing: Error Domain=com.apple.dt.xctest.ui-testing.error Code=10300 "Failed to background test runner within …
```

fix: set __ActivateSuspended to not block xctest run by popup

---

README.md
lib/usbmux/index.js

When `usbmuxd` is run without root user, it listens on a different path. `usbmuxd` itself [uses](https://github.com/libimobiledevice/libusbmuxd?tab=readme-ov-file#environment) this env var if it's given.
Tested manually with a real iPhone.

fix: get usbmuxd socket address from USBMUXD_SOCKET_ADDRESS environment

---

lib/base-service.js
lib/usbmux/transformer/usbmux-encoder.js
test/usbmux/usbmux-specs.js

Observed this, while going through the code base,
I think the BaseService is iterating by indices rather than actual values. 
Not sure of the implementation/ how it is handled internally, but looked like a bug.
So, Changed for...in loop to for...of to correctly iterate over event names rather than indices

fix: Loop in base-service.js
